### PR TITLE
Sdcard mount fix

### PR DESCRIPTION
**Pull request by ZeroChaos-**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
tested and confirmed on pad1, pad3, and phone

**Comment by tmossey** [comment]
tested and confirmed on pad2 and pad3

**Comment by tmossey** [comment]
:rocket:

**Comment by steev** [comment]
Copy pasta from over in 49.  Not sure why it showed up there, I commented at the bottom of the page where it showed the commit...

Sorry, I meant to comment on this sooner, not sure that it really matters for our usecase, but changing the /sdcard mount to /data/media/0 points to only the main user in a multi-user system. Not sure that we care, but something to be aware of.

**Comment by ZeroChaos-** [comment]
this is mounted at boot time by root.  It *should* be true location of /sdcard and it appears to be used by android later to fuse mount to /storage/emulated/legacy and then is symlinked to /sdcard

it sounds like you are suggesting that if I change users in android then sdcard would be pointing at a different location.  I guess we could readlink from /sdcard and mount it during bootpwn then unmount it after, but I'm not sure we even care.  Do you believe this use case is something to care about? Multi-user android system which a chroot user who isn't primary?

**Comment by tmossey** [comment]
I'm not sure this is something we care about, mainly because mounting /sdcard in the chroot is a matter of user convenience, not functionality. If /sdcard doesn't mount in a meaningful way for a non-primary user in the chroot, it doesn't really matter

**Comment by ZeroChaos-** [comment]
critique accepted, although I don't see that we need to care about this until a user complains.  Frankly since bootpwn must be run as root it will be hard to figure out what to mount so I don't see a need to worry about it until we actually have users using it that way.  thanks for the note, steev.

**Pull request merged**
