### PR TITLE
Handle shell defaults

### PR DESCRIPTION
**Pull request by ZeroChaos-**
this removes an unused file and makes our chroot jump into a login shell so it reads all the files to properly setup the environment for use.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
tested and confirmed

**Comment by ZeroChaos-** [comment]
http://www.tribeswell.com/wp-content/uploads/2012/08/Are-You-Not-Entertained-300x259.jpg

**Comment by ZeroChaos-** [comment]
oh, it's like this...

**Comment by awk9000** [comment]
Looks good to me, both vim and bash colors tested, as well as TPlink stuff on airodump, evilap, and wifite.  All working on stock CE image updated on this branch!

**Comment by awk9000** [comment]
Note: Haven't tested on a PwnPhone yet...

**Pull request merged**
