### PR TITLE
Unified interfaces

### PR DESCRIPTION
**Pull request by ZeroChaos-**
This PR unifies all of the scripts with a f_interface function to use the same function as sourced from px_interface_selector.sh

Proper features include:
intelligently setting available interfaces
optional default interface
colorized list based on if the interface is available currently or not
visible listing of default
countless safety checks to ensure success

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
As of this moment, and anticipating until this PR is merged, this branch is available for testing by running "cd /opt/pwnix/chef; ./update.sh pad"

**Comment by granolocks** [comment]
wow big change! but a good one methinks! :) is this ready for 1.6.4 or do you want to hold it for a bit more  testing?

**Comment by ZeroChaos-** [comment]
I've tested this, however, I'm the only one who has tested it.  Someone else needs to test it, and I'm not in a hurry to force this into 1.6.4 as it is not addressing any specific issue.

**Comment by tmossey** [comment]
I've been reviewing this periodically but I'd like to test it in the morning.

**Comment by tmossey** [comment]
Tested and confirmed working. Pls merge for sexiness

**Comment by tmossey** [comment]
:rocket:

**Comment by ZeroChaos-** [comment]
ordinarily I'd add a feature after this, but since there hasn't been a lot of testing, I added it just now instead.

Awk identified a potential issue with ettercap, nmap, and sslstrip which all need a valid ip address, so for those three scripts we now validate they have an ip.

As a free giveaway, I added in a note on what makes an interface valid or not, and colorized that message for clarity.

update is in pad as before.

**Comment by ZeroChaos-** [comment]
add command above overrides...

**Comment by granolocks** [comment]
lgtm once we get a bit more comments in there

**Comment by ZeroChaos-** [comment]
<stamp=rubber>:shippit:</stamp>
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAcQjRw&url=http%3A%2F%2Fwww.quickmeme.com%2FAdvice-Dog%2Fpage%2F32%2F&ei=28poVdquNMiMsAXx5IHIAg&bvm=bv.94455598,d.b2w&psig=AFQjCNE5yHJSJaQl8huCCOt-IyHwT0ECdg&ust=1433017432853824

**Comment by ZeroChaos-** [comment]
the pad update for testing has been removed.

**Comment by steev** [comment]
Sorry, I meant to comment on this sooner, not sure that it really matters for our usecase, but changing the /sdcard mount to /data/media/0 points to only the main user in a multi-user system.  Not sure that we care, but something to be aware of.

**Comment by ZeroChaos-** [comment]
Steev - if you manage to comment on the right PR, things might actually be noticed.

https://github.com/pwnieexpress/pwn_pad_sources/pull/48

**Pull request merged**
