### PR TITLE
if stupid hurt, this would be crippling

### PR DESCRIPTION
**Pull request by ZeroChaos-**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
fixes broken code introduced by me here: https://github.com/pwnieexpress/pwn_pad_sources/pull/115

**Comment by tmossey** [comment]
:disappointed:

**Comment by tmossey** [comment]
nah thank you for finding and fixing

**Comment by ZeroChaos-** [comment]
and introducing and breaking.

on the bright side, shellcheck is integrated into my editor now, so hopefully I'll be a touch less stupid.

**Pull request merged**
