### PR TITLE
NEEDS TESTING on pwnpad 1-3.5) - magic setup when kali chroot is missing

### PR DESCRIPTION
**Pull request by ZeroChaos-**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
Tested on PwnPhone 2014 (hammerhead) with Pwnpad stockchroot.img. /etc/product etc were automatically fixed as expected.

this process takes a few (10) minutes (unpacking >2GB) but works properly and allows us to build images with no kali chroot at all, and just drop the stockchroot.img in place and have it auto-setup.

**Comment by ZeroChaos-** [comment]
the image builder script looks like it needs some work (insight_api can't startup due to unable to open /dev/null despite it existing and having 666 permissions)  otherwise this looks good to go once tested on any pwnpad.

**Comment by ZeroChaos-** [comment]
fixed rspec issue

**Comment by ZeroChaos-** [comment]
merge https://github.com/pwnieexpress/pwnix_base_cookbook/pull/151 after this

**Comment by ZeroChaos-** [comment]
validated gold image generator and magic setup code.  good to go after any testing needed to feel comfortable on your side.

**Comment by ZeroChaos-** [comment]
update pack available to make testing easier.  "magic"

**Comment by tmossey** [comment]
tested it earlier this afternoon. the chroot was regenerated, but was missing /opt, which was probably the result of a bad stockchroot. i'm building a new one right now, then i'll test again.

**Comment by ZeroChaos-** [comment]
tested on tn8 with known good stockchroot.img and it worked perfectly.

rspec passes as well as it ever does on the mobile line.  I'm done testing, I say :rocket: :shipit:

**Comment by ZeroChaos-** [comment]
hermes seems to be crashing during startup and leaving a stale pidfile, but that bug doesn't appear to be related to this because restarting it makes it work fine.

**Comment by tmossey** [comment]
fml ran out of disk space during chroot creation. we know this works given a good stockchroot though.

**Comment by tmossey** [comment]
:rocket:

**Pull request merged**
