### PR TITLE
Chroot v2 support

### PR DESCRIPTION
**Pull request by ZeroChaos-**
the scripts work but I have not tested full function since none of my devices actually support squashfs in the kernel

### CODE REVIEW

**Comment by tmossey** [comment]
I can test this on shieldtablet after I flash it back.

**Comment by ZeroChaos-** [comment]
be sure to test one of the moto images, the sana ones are not ready yet.  and remember to rename it to stockchroot.sfs, I always forget

**Comment by ZeroChaos-** [comment]
must be merged at the same time as https://github.com/pwnieexpress/pwnix_base_cookbook/pull/178

**Comment by tmossey** [comment]
:rocket:

**Pull request merged**
