### PR TITLE
added check to determine path for dns2proxy whether kali1 or rolling

### PR DESCRIPTION
**Pull request by awk9000**

### CODE REVIEW

**Comment by steev** [comment]
👍

**Comment by ZeroChaos-** [comment]
this looks a bit cleaner to me, ready if you are

**Comment by granolocks** [comment]
LGTM

**Comment by ZeroChaos-** [comment]
NACK, test failed, commit incoming

**Comment by ZeroChaos-** [comment]
testing says this is correct for kali rolling.

**Comment by ZeroChaos-** [comment]
tested updated cleanup.  pass on kali rolling

**Comment by awk9000** [comment]
Tested latest commit on Kali 1 Nexus 7 verified working and killing processes properly.

**Pull request merged**
