### PR TITLE
support null interface in interface selector, sometimes I want to col…

### PR DESCRIPTION
**Pull request by ZeroChaos-**
…lect clients and offer no backend

do not commit until I put a comment about a successful test, this is more "wrote it on the airplane" code

### CODE REVIEW

**Comment by tmossey** [comment]
has this been tested yet?

**Comment by ZeroChaos-** [comment]
yeah, but not for a while now, I'll retest it

**Comment by ZeroChaos-** [comment]
now it works. ready for merge

**Comment by tmossey** [comment]
:rocket:

**Pull request merged**
