### PR TITLE
Testing required: Lol policy routing plus hostapd-wpe support

### PR DESCRIPTION
**Pull request by ZeroChaos-**

### CODE REVIEW

**Comment by sstelfox** [comment]
LGTM, I'll give it a test as well

**Comment by ZeroChaos-** [comment]
ran for ~16 hours on nexus 9 with alfa 051nhv2.  seems stable and functional.  Apologies to the neighbours.

**Comment by dallaswinger** [comment]
Tested good on Nexus 7 with TP-Link. 
No errors, works consistently and working with other tools such as strings watch, tcpdump, etc. 

Also doubly confirmed good on the 9 and alpha.

**Comment by sstelfox** [comment]
Changes look good... Charging my shield so I can test on that

**Comment by tmossey** [comment]
:rocket:

**Pull request merged**
