### PR TITLE
solve some things that were annoying me

### PR DESCRIPTION
**Pull request by ZeroChaos-**
It's nearly midnight, I can work on whatever I want.

### CODE REVIEW

**Comment by tmossey** [comment]
beautiful. has this been set of the changes been tested together?

**Comment by steev** [comment]
does the hci0 check fail if bluetooth is enabled on the device?

**Comment by ZeroChaos-** [comment]
I honestly have no idea what fails on what, I literally wrote all of this in a vacuum while on an airplane.  Testing begins now.  I have an update pack up called "annoy".  I'm sure there are bugs in this, like I said, it is *untested* at this point.  Most of this was run, but not all of it.

**Comment by ZeroChaos-** [comment]
(please note, every commit is also updating the update pack, so within 2 minutes of the commit an update pack is roughly available with the fixes)

**Comment by ZeroChaos-** [comment]
lol, that commit message was "learn to check $? properly" and my shell fixed it for me.

**Comment by steev** [comment]
And that's why you always escape your commit messages :heavy_check_mark:

**Comment by ZeroChaos-** [comment]
thanks for the commentary of my commit messages instead of the code, very helpful.

**Comment by ZeroChaos-** [comment]
further builds in the annoy branch will be built with https://github.com/pwnieexpress/pwnix_base_cookbook/pull/114 to pull in the new pxupdater.

**Comment by ZeroChaos-** [comment]
this has been extremely well tested at this point and is over 9000% better.  This will be merged after my first training class, some time tomorrow night.  If anyone else wants to share their test results, the update pack is up to date.

**Comment by ZeroChaos-** [comment]
clearly too tired to merge tonight, plus one more class to use for bug hunting, see you all tomorrow.

**Comment by ZeroChaos-** [comment]
This is all set from my end, to be merged after Tim drops his new pxupdater.apk in here

**Comment by tmossey** [comment]
ready :rocket:

**Pull request merged**
